repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--config=.tflint.hcl
      - id: terraform_trivy
        args:
          - --args=--severity=CRITICAL,HIGH
      - id: terraform_checkov