name: 'Terraform check'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  showinfo:
    runs-on: ubuntu-latest
    steps:
      - name: show commit message
        run: echo "commit - ${{github.event.head_commit.message}}"

  test:
    name: Test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: test stuff
        run: echo "Simulating tests"