name: 'Terraform check'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  showinfo:
    runs-on: ubuntu-latest
    steps:
      - name: show commit message
        run: echo "commit - ${{github.event.head_commit.message}}"
      - name: test stuff
        if: "contains(github.event.head_commit.message, '[!go deploy!]')"
        run: echo "Simulating tests"